<?php

namespace AppBundle\Repository;

/**
 * utentiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class utentiRepository extends \Doctrine\ORM\EntityRepository
{
}
